kind: Pod
apiVersion: v1
metadata:
  name: fleetman-pod
  namespace: nginx-test
  labels:
    app: fleetman
    release: "0"
spec:
  containers:
    - name: fleetman-container
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
  restartPolicy: Always

---

kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
  namespace: nginx-test
  labels:
    app: fleetman
    release: "0-5"
spec:
  containers:
    - name: fleetman-container
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
  restartPolicy: Always

# This Pod definition creates a single Pod named "nginx-pod" in the "nginx-test" namespace.
# The Pod runs an Nginx container exposing port 80 and has resource requests and limits defined for CPU and memory.
# The restart policy is set to "Always", ensuring the Pod is restarted automatically if it fails.
# Kubernetes Pod is the smallest deployable unit that can be created and managed in Kubernetes.