apiVersion: v1
kind: Service
metadata:
  name: contact-api-svc
  namespace: nginx-test
spec:
  selector:
    app: contact-api
  ports:
    - port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-api-deployment
  namespace: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-api
  template:
    metadata:
      labels:
        app: contact-api
    spec:
      containers:
        - name: contact-api
          image: amitweb2012/contact-service:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: MONGO_URI
              value: "mongodb://mongo-svc:27017/contacts"
