apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: nginx-test
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: next15-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: CONTACT_API_URL
              value: "http://contact-api-svc.nginx-test.svc.cluster.local:4000"
